In [3]:
import pandas as pd 
import requests 
from io import StringIO

# %conda install lxml
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
url = 'https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv'
res = requests.get(url, headers=headers).text
res = StringIO(res)

df = pd.read_csv(res)
df

,id,name,place,year,lat,long,lat_long
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57"
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57"
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57"
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57"
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57"
...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33"
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45"
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33"
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33"
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36"

In [10]:
count = len(df.loc[(df["year"] > 1588) & (df["year"] < 1592)])
print(count)

21

In [16]:
df['is_permanent'] = True

In [35]:
places = {'Geneva','Saxony','Tuscany','Ferrara'}
for i in df.index:
        if df.loc[i, 'place'] in places:
                df.loc[i, 'is_permanent'] = False
print(df.loc[df['place'].isin(places), ['place','is_permanent']])

       place  is_permanent
15    Geneva         False
212  Ferrara         False
313  Ferrara         False
401   Saxony         False
546  Ferrara         False
568   Saxony         False
581  Tuscany         False
582  Tuscany         False
701  Tuscany         False
799   Saxony         False
822   Geneva         False

In [49]:
change = ['Geneva', 'Grisons']
for i in df.index:
        if df.loc[i, 'place'] in change:
                df.loc[i, 'place'] = 'Swiss Cantons'
count = len(df.loc[df['place'] == 'Swiss Cantons'])
print(count)

210

In [60]:
df_agg = df.groupby('name').agg(
    years_present = ('name', 'count'),
    unique_ambs = ('place', 'nunique'),  
).reset_index().sort_values(by = 'unique_ambs', ascending = True).reset_index(drop = True)
df_agg

                                     name  years_present  unique_ambs
0                          Adhemar, Louis              2            1
1             Lancosme, Jacques Savary de              6            1
2                        Langrac, Jean de              3            1
3          Lansac, Guy de Saint-Gelais de              1            1
4                        Laval, Claude de              3            1
..                                    ...            ...          ...
149                        De Selve, Odet             11            3
150                  Marillac, Charles de             13            3
151                     De Selve, Georges             11            3
152  Noailles, Gilles de, Abbot of L'Isle             14            4
153             L'Aubespine, Sébastien de             10            4

[154 rows x 3 columns]